apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tozastation-istio-study
  region: ap-northeast-1

nodeGroups:
  - name: ng-1
    minSize: 2
    maxSize: 2
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
